// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `decode_mysql_cell`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<bool> testMysqlConnection({required String url}) =>
    RustLib.instance.api.crateApiSimpleTestMysqlConnection(url: url);

Future<List<String>> getMysqlDatabases({required String url}) =>
    RustLib.instance.api.crateApiSimpleGetMysqlDatabases(url: url);

Future<List<String>> getMysqlTables({
  required String url,
  required String database,
}) => RustLib.instance.api.crateApiSimpleGetMysqlTables(
  url: url,
  database: database,
);

Future<QueryResult> runMysqlQuery({
  required String url,
  required String database,
  required String query,
}) => RustLib.instance.api.crateApiSimpleRunMysqlQuery(
  url: url,
  database: database,
  query: query,
);

Future<QueryResult> getMysqlTableData({
  required String url,
  required String database,
  required String table,
}) => RustLib.instance.api.crateApiSimpleGetMysqlTableData(
  url: url,
  database: database,
  table: table,
);

Future<void> executeMysqlAction({
  required String url,
  required String database,
  required String query,
  required bool disableFk,
}) => RustLib.instance.api.crateApiSimpleExecuteMysqlAction(
  url: url,
  database: database,
  query: query,
  disableFk: disableFk,
);

class QueryResult {
  final List<String> columns;
  final List<List<String>> rows;

  const QueryResult({required this.columns, required this.rows});

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryResult &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows;
}
