// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_query_result`, `decode_mysql_cell`, `decode_mysql_row`, `get_or_create_pool`, `mysql_url`, `pool_cache`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<bool> testMysqlConnection({required String url}) =>
    RustLib.instance.api.crateApiSimpleTestMysqlConnection(url: url);

Future<SchemaOverview> getMysqlSchemaOverview({required String url}) =>
    RustLib.instance.api.crateApiSimpleGetMysqlSchemaOverview(url: url);

Future<QueryResult> runMysqlQuery({
  required String url,
  required String database,
  required String query,
}) => RustLib.instance.api.crateApiSimpleRunMysqlQuery(
  url: url,
  database: database,
  query: query,
);

Future<TablePageResult> runMysqlTablePage({
  required String url,
  required String database,
  required String dataQuery,
  required String countQuery,
}) => RustLib.instance.api.crateApiSimpleRunMysqlTablePage(
  url: url,
  database: database,
  dataQuery: dataQuery,
  countQuery: countQuery,
);

Future<void> executeMysqlAction({
  required String url,
  required String database,
  required String query,
  required bool disableFk,
}) => RustLib.instance.api.crateApiSimpleExecuteMysqlAction(
  url: url,
  database: database,
  query: query,
  disableFk: disableFk,
);

class DatabaseSchema {
  final String name;
  final List<String> tables;

  const DatabaseSchema({required this.name, required this.tables});

  @override
  int get hashCode => name.hashCode ^ tables.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatabaseSchema &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          tables == other.tables;
}

class QueryResult {
  final List<String> columns;
  final List<List<String>> rows;

  const QueryResult({required this.columns, required this.rows});

  @override
  int get hashCode => columns.hashCode ^ rows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueryResult &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          rows == other.rows;
}

class SchemaOverview {
  final List<DatabaseSchema> databases;

  const SchemaOverview({required this.databases});

  @override
  int get hashCode => databases.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SchemaOverview &&
          runtimeType == other.runtimeType &&
          databases == other.databases;
}

class TablePageResult {
  final QueryResult result;
  final PlatformInt64 totalRows;

  const TablePageResult({required this.result, required this.totalRows});

  @override
  int get hashCode => result.hashCode ^ totalRows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TablePageResult &&
          runtimeType == other.runtimeType &&
          result == other.result &&
          totalRows == other.totalRows;
}
